package com.securevault.ui.theme

import androidx.compose.ui.graphics.Color

// --- Light Scheme ---
val PrimaryLight = Color(0xFF1B6B4F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA4F4D2)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF4A635A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8DC)
val OnSecondaryContainerLight = Color(0xFF062018)
val TertiaryLight = Color(0xFF3A6472)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBEEAFA)
val OnTertiaryContainerLight = Color(0xFF001F28)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF8FAF7)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFF8FAF7)
val OnSurfaceLight = Color(0xFF191C1B)
val SurfaceVariantLight = Color(0xFFDBE5DE)
val OnSurfaceVariantLight = Color(0xFF404944)
val OutlineLight = Color(0xFF707973)
val OutlineVariantLight = Color(0xFFBFC9C2)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF2F4F1)
val SurfaceContainerLight2 = Color(0xFFECEFEB)
val SurfaceContainerHighLight = Color(0xFFE6E9E5)
val SurfaceContainerHighestLight = Color(0xFFE1E3E0)
val InverseSurfaceLight = Color(0xFF2E312F)
val InverseOnSurfaceLight = Color(0xFFEFF1EE)
val InversePrimaryLight = Color(0xFF7DDCB5)
val ScrimLight = Color(0xFF000000)

// --- Dark Scheme ---
val PrimaryDark = Color(0xFF7DDCB5)
val OnPrimaryDark = Color(0xFF003828)
val PrimaryContainerDark = Color(0xFF005138)
val OnPrimaryContainerDark = Color(0xFFA4F4D2)
val SecondaryDark = Color(0xFFB3CCC1)
val OnSecondaryDark = Color(0xFF1E352C)
val SecondaryContainerDark = Color(0xFF334B42)
val OnSecondaryContainerDark = Color(0xFFCCE8DC)
val TertiaryDark = Color(0xFFA2CEDE)
val OnTertiaryDark = Color(0xFF023442)
val TertiaryContainerDark = Color(0xFF1E4D5A)
val OnTertiaryContainerDark = Color(0xFFBEEAFA)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE1E3E0)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE1E3E0)
val SurfaceVariantDark = Color(0xFF404944)
val OnSurfaceVariantDark = Color(0xFFBFC9C2)
val OutlineDark = Color(0xFF8A938D)
val OutlineVariantDark = Color(0xFF404944)
val SurfaceContainerLowestDark = Color(0xFF0E1210)
val SurfaceContainerLowDark = Color(0xFF1D201F)
val SurfaceContainerDark = Color(0xFF212524)
val SurfaceContainerHighDark = Color(0xFF2C302E)
val SurfaceContainerHighestDark = Color(0xFF363A38)
val InverseSurfaceDark = Color(0xFFE1E3E0)
val InverseOnSurfaceDark = Color(0xFF2E312F)
val InversePrimaryDark = Color(0xFF1B6B4F)
val ScrimDark = Color(0xFF000000)

// --- Functional / Semantic Colors ---
val StrengthVeryWeak = Color(0xFFD32F2F)
val StrengthWeak = Color(0xFFF57C00)
val StrengthMedium = Color(0xFFFBC02D)
val StrengthStrong = Color(0xFF388E3C)
val StrengthVeryStrong = Color(0xFF1B6B4F)

val SecurityModeColor = Color(0xFF7B1FA2)
val SecurityModeContainerLight = Color(0xFFF3E5F5)
val SecurityModeContainerDark = Color(0xFF4A148C)

val FavoriteColor = Color(0xFFFFB300)

val PasswordDisplayBackground = Color(0xFF1A1A2E)
